version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains information about brands"
    columns:
      - name: id_brand
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Name of the brand"

  - name: stg_local_bike__categories
    description: "This model contains information about product categories"
    columns:
      - name: id_category
        description: "Primary key, unique identifier for each category"
        tests:
            - not_null
            - unique
      - name: category_name
        description: "Name of the brand"

  - name: stg_local_bike__customers
    description: "This model contains information, including private data, about customers"
    columns:
      - name: id_customer
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: phone
        description: "Phone number of the customer"
      - name: email
        description: "Email address of the customer"
      - name: street
        description: "Street name of the customer"
      - name: city
        description: "City name of the customer"  
      - name: state
        description: "State name of the customer"
      - name: zipcode
        description: "Zipcode of the city of the customer"

  - name: stg_local_bike__order_items
    description: "This model contains informations about order items"
    columns:
      - name: order_item_id
        description: "Primary key - generated by concatenating order_id and item_id"
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: item_id
        description: "Item_id of the order item"
      - name: product_id
        description: "id of the product of the order item"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__products')
              field: id_product
      - name: quantity
        description: "Quantity of the item"
      - name: list_price
        description: "List price of the item"
      - name: discount
        description: "Discount applied to the order item"  
      - name: total_order_item_amount
        description: "Total amount for the order item - calculated by multiplying list_price by quantity and multiplying this by the 1 minus the discount percentage"
  
  - name: stg_local_bike__orders
    description: "This model contains information about orders"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order"
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Id of the customer that made the order"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__customers
              to: ref('stg_local_bike__customers')
              field: id_customer
      - name: order_status
        description: "Status of the order - represented by a number"
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: [1,2,3,4]
              quote: false
      - name: order_created_at
        description: "Creation date of the order"
      - name: required_at
        description: "Date at which the order needs to be delivered"
      - name: shipped_at
        description: "Shipping date of the order"
      - name: store_id
        description: "Id of the store in which the order was made"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__stores
              to: ref('stg_local_bike__stores')
              field: id_store
      - name: staff_id
        description: "Id of the salesperson that made the order"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__staffs
              to: ref('stg_local_bike__staffs')
              field: id_staff

  - name: stg_local_bike__products
    description: "This model contains information about products"
    columns:
      - name: id_product
        description: "Primary key, unique identifier for each product"
        tests:
            - unique
            - not_null
      - name: product_name
        description: "Name of the product"
      - name: brand_id
        description: "Id brand of the brand of the product"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__brands
              to: ref('stg_local_bike__brands')
              field: id_brand
      - name: category_id
        description: "Id category of the category of the product"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__categories
              to: ref('stg_local_bike__categories')
              field: id_category
      - name: model_year
        description: "Year of the model of the product"
      - name: list_price
        description: "List price of the product"

  - name: stg_local_bike__staffs
    description: "This model contains information about staffs"
    columns:
      - name: id_staff
        description: "Primary key, unique identifier for each staff member/salesperson"
        tests:
            - unique
            - not_null
      - name: first_name
        description: "First name of the salesperson"
      - name: last_name
        description: "Last name of the salesperson"
      - name: email
        description: "Email address of the salesperson"
      - name: phone
        description: "Phone number of the salesperson"
      - name: active
        description: "Boolean flag to specify is the salesperson is still active/still works in the company"
      - name: store_id
        description: "Id of the store in which the salesperson works"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__stores
              to: ref('stg_local_bike__stores')
              field: id_store
      - name: manager
        description: "Id of the manager of the salesperson"

  - name: stg_local_bike__stocks
    description: "This model contains information about stocks of products in stores"
    columns:
      - name: stock_id
        description: "Primary key - generated by concatenating store_id and product_id"
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Id of the store in which the salesperson works"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__stores
              to: ref('stg_local_bike__stores')
              field: id_store
      - name: product_id
        description: "Id of the product"
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__products')
              field: id_product
      - name: quantity
        description: "Stock quantity of the product in the store"

  - name: stg_local_bike__stores
    description: "This model contains information about stores"
    columns:
      - name: id_store
        description: "Primary key, unique identifier for each store"
        tests:
            - unique
            - not_null
      - name: store_name
        description: "Name of the store"
      - name: phone
        description: "Phone number of the store"
      - name: email
        description: "Email address of the store"
      - name: street
        description: "Street name of the store"
      - name: city
        description: "City name of the store"
      - name: state
        description: "State name of the store"
      - name: zipcode
        description: "Zipcode of the city of the store"